
// import localFont from "next/font/local";
// import "./globals.css";
// import AuthWrapper from "./auth-wrapper";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });





// export const metadata = {
//   title: "BARAI",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
         
//         <AuthWrapper>
//         {children}
        
//         </AuthWrapper>
       
//       </body>
//     </html>
//   );
// }



import localFont from "next/font/local";
import "./globals.css";
import AuthWrapper from "./auth-wrapper";

import { Toaster } from "react-hot-toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});





export const metadata = {
  title: "BARAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Toaster/>
         
        <AuthWrapper>
        
        {children}
        
        </AuthWrapper>
        
       
      </body>
    </html>
  );
}